owner: willhackett # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: MTA STS
    url: https://mta-sts.willhackett.com/.well-known/mta-sts.txt
  - name: Notes
    url: https://notes.willhackett.com
  - name: Landing
    url: https://willhackett.com
  - name: Stats
    url: https://digistats.ch
  - name: NS0
    check: 'tcp-ping'
    url: ns0.willhackett.com
    port: 53
  - name: NS1
    check: 'tcp-ping'
    url: ns1.willhackett.com
    port: 53
  - name: SMTP IN1
    url: in1-smtp.messagingengine.com
    port: 587
    check: 'tcp-ping'
  - name: SMTP IN2
    url: in2-smtp.messagingengine.com
    port: 587
    check: 'tcp-ping'
  - name: SMTP OUT1
    url: fout-b1-smtp.messagingengine.com
    port: 587
    check: 'tcp-ping'
  - name: SMTP OUT2
    url: fout-b2-smtp.messagingengine.com
    port: 587
    check: 'tcp-ping'
  - name: SMTP OUT3
    url: fout-b3-smtp.messagingengine.com
    port: 587
    check: 'tcp-ping'
  - name: SMTP OUT4
    url: fout-b4-smtp.messagingengine.com
    port: 587
    check: 'tcp-ping'
  - name: SMTP OUT5
    url: fout-b5-smtp.messagingengine.com
    port: 587
    check: 'tcp-ping'
  - name: SMTP OUT6
    url: fout-b6-smtp.messagingengine.com
    port: 587
    check: 'tcp-ping'
  - name: SMTP OUT7
    url: fout-b7-smtp.messagingengine.com
    port: 587
    check: 'tcp-ping'
  - name: SMTP OUT8
    url: fout-b8-smtp.messagingengine.com
    port: 587
    check: 'tcp-ping'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.willhackett.com
  # baseUrl: /status
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
