owner: willhackett # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: MTA STS
    url: https://mta-sts.willhackett.com/.well-known/mta-sts.txt
  - name: Notes
    url: https://notes.willhackett.com
  - name: Landing
    url: https://willhackett.com
  - name: Stats
    url: https://digistats.ch
  - name: Mail
    url: https://fastmailstatus.com/summary.json
    __dangerous__body_down_if_text_missing: '"status":"UP"'
  - name: CDN
    url: https://status.bunny.net/index.json
    __dangerous__body_down_if_text_missing: 'All Systems Operational'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.willhackett.com
  # baseUrl: /status
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
